spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wxshop?serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  config-location: classpath:db/mybatis/config.xml